# Generated by Django 5.2 on 2025-04-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('social', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_residencial', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('historico', models.TextField(blank=True, null=True)),
                ('ultimo_atendimento', models.DateField(blank=True, null=True)),
                ('data_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_residencial', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('habilidades_profissionais', models.TextField(blank=True, null=True)),
                ('apontamentos', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitado', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_agendado', models.DateField(verbose_name='Data Agendada')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('servicos', models.TextField(verbose_name='Serviços')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('valor_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Previsto (R$)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.cliente', verbose_name='Cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_solicitado'],
            },
        ),
    ]
